Update people.json
UoMResearchIT/RSESkillsGraph pull request #22
Opened 2023-08-25 15:14 UTC by TheresaTeng

Updated Theresa's interest.

2023-09-14 16:50 UTC, aharwood2 requested changes
Sorry for deleting this branch -- I didn't see the open PR! Some changes required based on the controlled vocab really. We need an auto check for this really.

2023-09-14 16:50 UTC, aharwood2 commented on people.json
> +            "Jira",
"Jira" should be "Jira (software)"

2023-09-14 16:50 UTC, aharwood2 commented on people.json
> +            "Wagtail",
Should be "Wagtail (CMS)"

2023-09-18 08:45 UTC, TheresaTeng commented on people.json
> +            "ASP.NET Blazor",
Thank you. All the terms you mentioned have been changed.

2023-09-18 08:49 UTC, aharwood2 approved these changes
Changes to vocab all made. Happy for you to merge.

2023-09-18 08:54 UTC, merged